ALTER TABLE users_environments    drop  CONSTRAINT users_environments_fk1 
;
ALTER TABLE users_environments    drop  CONSTRAINT users_environments_fk2 
;
ALTER TABLE environments_hostnames    drop  CONSTRAINT environments_hostnames_fk1 
;
ALTER TABLE environments_hostnames    drop  CONSTRAINT environments_hostnames_fk2 
;
ALTER TABLE ROLES_DATABASES    drop  CONSTRAINT ROLES_databases_fk1 
;
ALTER TABLE ROLES_DATABASES    drop  CONSTRAINT ROLES_databases_fk2 
;
ALTER TABLE USERS_SQL_ACTIVITIES    drop  CONSTRAINT users_activities_fk1 
;
ALTER TABLE USERS_ROLES    drop  CONSTRAINT users_ROLES_fk1 
;
ALTER TABLE USERS_ROLES    drop  CONSTRAINT users_ROLES_fk2 
;


DROP TABLE DATABASES;
DROP TABLE ENVIRONMENTS;
DROP TABLE ENVIRONMENTS_HOSTNAMES;
DROP TABLE HOSTNAMES;
DROP TABLE LOG_MESSAGES;
DROP TABLE BACKGROUND_QUERIES;
DROP TABLE ROLES;
DROP TABLE ROLES_DATABASES;
DROP TABLE SQL_STATEMENTS;
DROP TABLE USERS;
DROP TABLE USERS_ENVIRONMENTS;
DROP TABLE USERS_ACTIVITIES;
DROP TABLE USERS_ROLES;
DROP TABLE USERS_SQL_ACTIVITIES;
DROP SEQUENCE seq_background_queries;
DROP SEQUENCE seq_users_sql_activities;
DROP SEQUENCE seq_log_messages;